### ISSUE TITLE
A probability sum over FieldTiles

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/healpix-alchemy#30]
Right now, the examples focus on single field tiles, like "What is the probability contained within each field?"

This is great, however, for example for ZTF, which has many quadrants within one field and therefore many FieldTiles for a single field, we are more interested in the sum of probabilities within a given set of FieldTiles. I expect a combination of the "What is the combined area of fields 1000 through 2000?" example (instead getting the FieldTile id's corresponding to a given field) and then summing the probabilities calculated in the "What is the probability contained within each field?" example, would do it, but would require a loop over fields. Is there a faster way?

**Comment by lpsinger** [comment]
Even a single quadrant would have many FieldTile rows, because FieldTile merely represents a HEALPix tile belonging to a region.

I think you are describing the "What is the combined area of fields 1000 through 2000?" example. Just replace the `FieldTile.id.between(1000, 2000)` clause with the appropriate condition.

**Comment by mcoughlin** [comment]
Great point Leo. Closing.
